'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Repair_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        '''  재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Activity_Monitor_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Activity_Monitor_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property add_to_database_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_to_database_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property add_to_database_241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_to_database_241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property arrow_double() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_double", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property arrow_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property arrow_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Autoship_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Autoship_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Autoship_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Autoship_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property barcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property barcode_2d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barcode_2d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bytecode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bytecode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property checkmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Close_Box_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_Box_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property delete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property DeviceData() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeviceData", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property document_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Document_Open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Document_Open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property EXCEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXCEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property excel2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property folder_beige() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_beige", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property folder_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property folder_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property folder_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property folder_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Globe_Download_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Globe_Download_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property HearCount1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HearCount1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property HearCount2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HearCount2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property index() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Map_Out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Map Out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property minus_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Mounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property None_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("None Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Open_Folder_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open_Folder_Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property order_history_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("order_history_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property order_history_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("order_history_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ordering_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordering_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ordering_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordering_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ordering_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordering_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ordering_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordering_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ordering_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordering_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property phone_settings_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone_settings_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property picture_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property picture_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property plus_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property plus_blue_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_blue_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property plus_blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property PMIC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PMIC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property PMIC_Reg_FAIL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PMIC Reg FAIL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Process_Info_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Process_Info_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Process_Warning_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Process_Warning_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property product_sales_report_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("product_sales_report_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property RCD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RCD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property RCD_Count() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RCD Count", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property remove_from_database_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_from_database_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save_add2_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_add2_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save_delete2_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_delete2_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Search_121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Setting_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Setting_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property sitemap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sitemap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property SRB_CRB_Test_Fail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SRB CRB Test Fail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Star_Full_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Full_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property TEST_FOLDER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEST_FOLDER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property vmware() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vmware", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property web_management() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("web_management", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property YUJIN_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YUJIN_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
